branch-defaults:
  master:
    environment: majportfolio-env
environment-defaults:
  majportfolio-env:
    branch: null
    repository: null
global:
  application_name: majportfolio
  default_environment: majportfolio-env
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  repository: https://github.com/mattandbucs34/majportfolio.git
  workspace_type: Application